
@urlDev=http://localhost:9000
@urlPro=https://kon-service.onrender.com


GET {{urlDev}}/api/v1/checkhealth

###
POST {{urlDev}}/api/v1/auth/signinwithusername
Content-Type: application/json

{
  "username": "admin",
  "password": "Changeit"
}

###
POST {{urlDev}}/api/v1/auth/signinwithusername
Content-Type: application/json

{
  "username": "khakhung",
  "password": "123abcxxx"
}

###
POST {{urlDev}}/api/v1/auth/signup
Content-Type: application/json

{
  "userId": "khakhung",
  "username": "khakhung",
  "phone": "0004380984",
  "displayName": "Kha Bo Do",
  "email": "khabd@xyz.com",
  "password": "123abcxxx",
  "repeat_password": "123abcxxx"
}
