
@urlDev=http://localhost:9000
@urlPro=https://kon-service.onrender.com


GET {{urlDev}}/api/v1/checkhealth

###
POST {{urlPro}}/api/v1/auth/signup
Content-Type: application/json

{
  "userId": "khabodoconbocu",
  "name": "Kha bo do",
  "email": "hcaio@ckhansu.vn",
  "password": "123abcxxx"
}
