
@urlDev=http://localhost:9000


GET {{urlDev}}/api/v1/checkhealth

###
POST {{urlDev}}/api/v1/auth/signup
Content-Type: application/json

{
  "userId": "khabodo",
  "name": "Phong",
  "email": "hcaio@ckhan.vn",
  "password": "123abc"
}
