version: "3.1"

services:
  # node-app:
  #   image: ntnghiatn/node-app
  #   build: 
  #     context: .
  #   container_name: node-app
  #   restart: unless-stopped
  #   volumes: 
  #     - ./logs:/home/node/app/logs
  #   ports:
  #     - "9000:9000"
  #   networks: 
  #     - proxy_network

  mongo:
    # To create this service, Compose will pull the mongo
    image: mongo:6.0.3
    container_name: mongo
    restart: unless-stopped
    # This tells Compose that we would like to add environment variables
    # from a file called .env, located in our build context.
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ADMIN_PWD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - 27017:27017
    volumes:
      - ./addons/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        # The named volume dbdata will persist the data stored in Mongo’s default data directory, /data/db.
        # This will ensure that you don’t lose data in cases where you stop or remove containers.
      - dbdata:/data/db
    networks: 
      - proxy_network

volumes: 
  dbdata:

networks:
  proxy_network:
    name: proxy_network
   
