version: "3.1"

services:
  node-app:
    image: ntnghiatn/node-app
    build: 
      context: .
    container_name: node-app
    restart: unless-stopped
    volumes: 
      - ./logs:/home/node/app/logs
    ports:
      - "9000:9000"
    networks: 
      - node-network-1
  
networks: 
  node-network-1:    
