@urlDev=http://localhost:9000/api/v1
@urlPro=https://kon-service-q2bs.onrender.com/api/v1
@url={{urlPro}}


GET {{url}}/checkhealth

### put
POST {{url}}/comment
Content-Type: application/json
x-token: 

{
  "slug": "34033750",
  "discuss_id": 1,
  "isDEL": "NO",
  "text": "I really like .... 34033750",
  "author": { 
    "name": "drodgers", 
    "avt": ""
  }
}

###
