@urlDev=http://localhost:9000/api/v1
@urlPro=https://kon-service-q2bs.onrender.com/api/v1
@url={{urlDev}}
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjViYzU0N2E3MTFjYzMxMzA3NTJkMTBhXCIsXCJyb2xlc1wiOltudWxsXX0iLCJwcm0iOiIzYTNlZThmZWM5MDQwNTI0YzIyYmFkZGZmZGQ1YTJmNDA0NTdhN2EyNDYzOGYzNGYxZjUxY2ZiM2JjOWI5ZWM3YTg0ZGU1OGNkZTEzYjlkZTcwMWY4N2M4MzViZTM4ZGFlN2YzMzc3NTUwNzM0YzFkNmQ0ODEwOGU0ZDNmYTRhMSIsImlhdCI6MTcwNjg3OTg4NCwiZXhwIjoxNzA2ODgwNzg0fQ.MzBP2W_skgNLWU7_2AOUomFsaM-_xFGNUp1rBeZnIKNJsTO0S2nBPVSq2QhD6VPsM8vScLnTIuUGQVyYcnJZjYMfq5eJHBJYN9QEumHPK9rvturSNIqeaKsgHX6KbrTHsOT8aGK3tR7kfuRtlyeHKJ_Z6YKDKSPNqxwaf4NSwrc
@refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjViYzU0N2E3MTFjYzMxMzA3NTJkMTBhXCJ9IiwicHJtIjoiMjYyYTE3Mjk4NzIzZTU3YzA1ODg2YjgyMDA2NjBmYTMwYTkwNzA0MWFhMGVlNzJjMDI5ZDI3YWQwM2U5NWM0YzE5MGRiMjEwYmM1MDQ2NGJjMGRlNjc1ZjhmZjQzOTI4YWM0YzAyZGE5MWRkMWZhMmY2NDg0NzA3NWY0YTUzZDciLCJpYXQiOjE3MDY4Nzk4ODQsImV4cCI6MTcwNzQ4NDY4NH0.Tid4nmcPnWuRBzVL7OGAG8FrJvskUOUSfRi6PpEtl4DpsKHZSZyKKzLj_lz5zamRCi265298-cnitoLOoOOv9CxMHYgeWMc-_naSnINDAU_CCVRD_CkdC76YPNtgG_o2uJejtE4mkkNroMyz_m-RlOJVO9EpAMMnYE65XGqeu3c

GET {{url}}/me
Content-Type: application/json
x-token: {{refreshToken}}

###
GET {{url}}/checkhealth

###
GET {{url}}/auth/refreshtoken
Content-Type: application/json
x-token: {{refreshToken}}

### Login 
POST {{url}}/auth/signinwithusername
Content-Type: application/json

{
  "username": "conbocu",
  "password": "123abcxxx"
}

###
POST {{url}}/auth/signup
Content-Type: application/json

{
  "userId": "teo",
  "username": "conbocu",
  "phone": "098489009511",
  "displayName": "Con",
  "email": "conbocu@xyz.com",
  "password": "123abcxxx",
  "repeat_password": "123abcxxx"
}
