@urlDev=http://localhost:9000/api/v1
@urlPro=https://kon-service-q2bs.onrender.com/api/v1
@url={{urlDev}}

### GetAll
GET {{url}}/agent/list
Content-Type: Application/json
x-api-key: CCMUD90YvklWvyUNt9n3QtsNoSHzK7U0



### Create Agent
POST {{url}}/agent/create
Content-Type: Application/json
x-api-key: CCMUD90YvklWvyUNt9n3QtsNoSHzK7U0

{
  "agentId": "id_dfgtttygdgdgdy",
  "code": "088583999",
  "title": "title 1",
  "description": "desc 1",
  "notes": "note 1"
  }
