@urlDev=http://localhost:9000/api/v1
@urlPro=https://kon-service-q2bs.onrender.com/api/v1
@url={{urlPro}}
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyMzk2NThiYzFiMDYzNGJhMzEwNGYzXCIsXCJyb2xlc1wiOltcIkdVRVNUXCIsXCJBRE1JTlwiXX0iLCJwcm0iOiIxZmRjZmNhYWM5YmUzYTU4MGVjYmQwYWMzOGRjMzBkNmZhZGI2OGFhNjAwOWQ5NzcyYmI5ZWVhYTg3NjY4MzU0MzVkY2U5NDJmNjYwZDUwZTU0NzUxMTAzMmYwYjY1Mzg1YzI1NjM3MzJjYzlkMTJkNDhmM2NlMzk4NTgzYWQ0YiIsImlhdCI6MTY5NjkxODMzNCwiZXhwIjoxNjk2OTE4Mzk0fQ.DGjtxnHq7LO8ldXy_lrkhI0fYwvlNFxWgwHwod3seNnn8bMXMEY-iTFP_zFq8BYeEve4tArVoiyybF-rBnifrWXmpENPgq4OT0fdrFZ6rsixUpT7wqqbpaR54ioilUqFQLBZg8I2fj9l1JyZ7prM0kppUYXU2nVze8sPezYiD_w

### GetAll
GET {{url}}/admin/apikey/list
Content-Type: Application/json
x-api-key: CCMUD90YvklWvyUNt9n3QtsNoSHzK7U0
x-token: {{accessToken}}

### Create
POST {{url}}/admin/apikey/create HTTP/1.1
Content-Type: application/json
x-api-key: CCMUD90YvklWvyUNt9n3QtsNoSHzK7U0
x-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiY2UyYmYwOTctYWFhNS00YmI0LWE5YmMtNzI2ZjQzYTg2ZjBiXCIsXCJ1c2VybmFtZVwiOlwia2hha2h1bmdcIixcInJvbGVzXCI6W1wiR1VFU1RcIixcIkFETUlOXCJdfSIsInBybSI6IjY3N2Y0MDcwNzBiODhlNDZlNjQwZmFmZjY2ZjliY2M4Y2U4NjQwMmFjNTM0MTQ1MDdhMjUzNzAwMTI1NjdlYjVhZDVlZmVlOWQ2M2U2NzQwY2NhNGQwNmZmMGU3Y2EyZWVlZDhlNzZlMGMxYmU1ZjQzOTViZTJiMDNhOTYyZGQxIiwiaWF0IjoxNjk2ODc2ODk0LCJleHAiOjE2OTcwNDk2OTR9.edTjbF9mA_fS-SrMyVF2mHSN8TLrZdDKZVYCfGrYzRXB8RgFRCmovGT8GdWqxQQhbBEZ98yeau0Mu8yg1OK9pvg6JW6ISOsvdbn-uQ60OMqFiZQ0KIn7OFeEpvqrH4muYoFaEooSFWrGncJ7n9BzZ7dq3U9S6tEMbH_xp-1lQu8

{
  "key": "CCMUD90YvklWvyUNt9n3QtsNoSHzK7U985",
  "permissions": ["GENERAL","QUAN"],
  "comments": ["To be used by the xyz vendor"],
  "version": 1
}
