@urlDev=http://localhost:9000/api/v1
@urlPro=https://ka-gen-api.onrender.com/api/v1
@url={{urlDev}}

@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyMzk2NThiYzFiMDYzNGJhMzEwNGYzXCIsXCJyb2xlc1wiOltcIktBTE5LTTA2TDJcIixcIktBTE5LTTFDSU5cIl19IiwicHJtIjoiOTI1Y2E1YjRkNTM0M2E2MGEyYzA1YTVkNmEwNTRmMmJlNjU2YmYwOGY5OGZkY2QxYTVlNjk4OTM4ZTQ2NWM1MDU3MjhmMzRjNDRiYjA3ZDZhMDk4MGZlNGFmMmIzODNlOWZmMjcyNzk3ODY5NDFhYTM1OTQyMWExYzdiZTcyODIiLCJpYXQiOjE2OTcwNDczMDUsImV4cCI6MTY5NzA0ODIwNX0.I4EIlaSKQb-TMFJWVoyEdtwNrLSF_VEQRbVRx9_9L5sLeVrIyoksEQhGRITsGR-1L01LCxZuNzvGT5Nj7h-fBLRKMb8xu-fu6hVapPVyF79nDxXIyRcn8pqWS0W6TQiB--YGV4hFRJDGhw4iqbuOPVcrF1ln9-F_M3V2xGFtjuo

@refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyMzk2NThiYzFiMDYzNGJhMzEwNGYzXCJ9IiwicHJtIjoiZWI0YzA0Yjg3NmI0ZDVhZGUxNzI3NmUzZTE3ODQ1MjgyNzNjMTUyMTJiZmYwYzFlNTcyMmJjZDkyNTY4YTEwNDYxNzM1MWI4OTI0NzNlMzUwYzFkM2RkMzEyMWNlZWEyMjk2Mzg3NWUzYmVlOTM4MzBkYTkxODYxM2UzNzc4MTciLCJpYXQiOjE2OTcwNDczNzQsImV4cCI6MTY5NzY1MjE3NH0.Eta-gSn1uv8yKq4pAtgi5InVDDq649stCyZHqd3zwEhWjF7HJeYNxR-XCweBbBzV9vK2D_5LNtR1jIqm5SjeQFnyNtwOoe-ouR3l6afC0Jh77lQSNilVCSGZEOoU8ajQwwR4enTKKiRFaWNRP0wPpDykC31OceTCFUuGwa9T2AA

POST {{url}}/roles/create
Content-Type: application/json
x-token: {{accessToken}}

{
  "code":  "CREATOR",
  "key": "CREATOR",
  "description": "CREATOR",
  "notes": "CREATOR"
}

###
GET {{url}}/roles?code=cUSTOMER
Content-Type: application/json
x-token: {{refreshToken}}

###
GET {{url}}/roles/652592f5f94f07e658330213
Content-Type: application/json
x-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyNGYyNjBiYWU2NDhjMmNmNDQyNGI1XCIsXCJyb2xlc1wiOltcIktBTE5LTTFDSU5cIl19IiwicHJtIjoiOWQ3ZjJjODVlN2Y2OTI4NDY0ODNhMWY2NjQ4M2EzNTAwZmIwZTQ5MjZjNmIwYmFiMGQ5MTYxNTI2OWQ0NTAxNTNmZTNiMTc3MTgwMmM3YWIzMTk0Zjg2MDk5ZWUwNTgwNWI4ZjE5M2RhMWFiNGEzODY3OWEwMTRhZGUwOGQzNmIiLCJpYXQiOjE2OTY5NjA0MDYsImV4cCI6MTY5NzU2NTIwNn0.Njz5gSyBbs99Luw4MhPXD4Njh2BZhv2rdjzbBXm2qAix42jKdEmLbDPwYHOFvEiHu2tREiq98f_RMSwOBL0Ygvyf7VtIQGkBZEUnNhk1InBNReKD_njGFtK5df_ioTFf2y0ivw4RqiDSvUVdesrzipFLh8sDB0k02TKgrbsN8GQ

###

POST {{url}}/admin/putrole
Content-Type: application/json

{
  "isDEL": "NO",
  "roleId": "parner",
  "code":  "vkl_007",
  "key": "vkl_007",
  "description": "update vkl khi ko co lan 1",
  "notes": "update lan 1"
}

###
DELETE {{url}}/admin/role/delete/lf1e965n
Content-Type: application/json