@urlDev=http://localhost:9000/api/v1
@urlPro=https://kon-service-q2bs.onrender.com/api/v1
@url={{urlPro}}

POST {{url}}/roles/create
Content-Type: application/json
x-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyNGYyNjBiYWU2NDhjMmNmNDQyNGI1XCIsXCJyb2xlc1wiOltcIktBTE5LTTFDSU5cIl19IiwicHJtIjoiOWQ3ZjJjODVlN2Y2OTI4NDY0ODNhMWY2NjQ4M2EzNTAwZmIwZTQ5MjZjNmIwYmFiMGQ5MTYxNTI2OWQ0NTAxNTNmZTNiMTc3MTgwMmM3YWIzMTk0Zjg2MDk5ZWUwNTgwNWI4ZjE5M2RhMWFiNGEzODY3OWEwMTRhZGUwOGQzNmIiLCJpYXQiOjE2OTY5NjA0MDYsImV4cCI6MTY5NzU2NTIwNn0.Njz5gSyBbs99Luw4MhPXD4Njh2BZhv2rdjzbBXm2qAix42jKdEmLbDPwYHOFvEiHu2tREiq98f_RMSwOBL0Ygvyf7VtIQGkBZEUnNhk1InBNReKD_njGFtK5df_ioTFf2y0ivw4RqiDSvUVdesrzipFLh8sDB0k02TKgrbsN8GQ

{
  "code":  "CREATOR",
  "key": "CREATOR",
  "description": "CREATOR",
  "notes": "CREATOR"
}

###
GET {{url}}/roles?code=cUSTOMER
Content-Type: application/json
x-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyNGYyNjBiYWU2NDhjMmNmNDQyNGI1XCIsXCJyb2xlc1wiOltcIktBTE5LTTFDSU5cIl19IiwicHJtIjoiOWQ3ZjJjODVlN2Y2OTI4NDY0ODNhMWY2NjQ4M2EzNTAwZmIwZTQ5MjZjNmIwYmFiMGQ5MTYxNTI2OWQ0NTAxNTNmZTNiMTc3MTgwMmM3YWIzMTk0Zjg2MDk5ZWUwNTgwNWI4ZjE5M2RhMWFiNGEzODY3OWEwMTRhZGUwOGQzNmIiLCJpYXQiOjE2OTY5NjA0MDYsImV4cCI6MTY5NzU2NTIwNn0.Njz5gSyBbs99Luw4MhPXD4Njh2BZhv2rdjzbBXm2qAix42jKdEmLbDPwYHOFvEiHu2tREiq98f_RMSwOBL0Ygvyf7VtIQGkBZEUnNhk1InBNReKD_njGFtK5df_ioTFf2y0ivw4RqiDSvUVdesrzipFLh8sDB0k02TKgrbsN8GQ

###
GET {{url}}/roles/652592f5f94f07e658330213
Content-Type: application/json
x-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyNGYyNjBiYWU2NDhjMmNmNDQyNGI1XCIsXCJyb2xlc1wiOltcIktBTE5LTTFDSU5cIl19IiwicHJtIjoiOWQ3ZjJjODVlN2Y2OTI4NDY0ODNhMWY2NjQ4M2EzNTAwZmIwZTQ5MjZjNmIwYmFiMGQ5MTYxNTI2OWQ0NTAxNTNmZTNiMTc3MTgwMmM3YWIzMTk0Zjg2MDk5ZWUwNTgwNWI4ZjE5M2RhMWFiNGEzODY3OWEwMTRhZGUwOGQzNmIiLCJpYXQiOjE2OTY5NjA0MDYsImV4cCI6MTY5NzU2NTIwNn0.Njz5gSyBbs99Luw4MhPXD4Njh2BZhv2rdjzbBXm2qAix42jKdEmLbDPwYHOFvEiHu2tREiq98f_RMSwOBL0Ygvyf7VtIQGkBZEUnNhk1InBNReKD_njGFtK5df_ioTFf2y0ivw4RqiDSvUVdesrzipFLh8sDB0k02TKgrbsN8GQ

###

POST {{url}}/admin/putrole
Content-Type: application/json

{
  "isDEL": "NO",
  "roleId": "parner",
  "code":  "vkl_007",
  "key": "vkl_007",
  "description": "update vkl khi ko co lan 1",
  "notes": "update lan 1"
}

###
DELETE {{url}}/admin/role/delete/lf1e965n
Content-Type: application/json