@urlDev=http://localhost:9000/api/v1
@urlPro=https://kon-service-q2bs.onrender.com/api/v1
@url={{urlDev}}
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyMzk2NThiYzFiMDYzNGJhMzEwNGYzXCIsXCJyb2xlc1wiOltcIkdVRVNUXCIsXCJBRE1JTlwiXX0iLCJwcm0iOiJhMmI2MDUzMTAyOWZiNmYxMDFiMGQ3OTk1NjcyNjU0N2NjMGNjOGY5NjIxNDMwMzcyZjU0MTAwYjQxNmMwMzIyMzIyYjE2MDI3OTkzMWQ5MmZlOTY3YmIzYTZmNWRkNWNlYjk0MzM0MDg1NzZhYjZkMTRmN2MyZDgzZWRhMGIzNiIsImlhdCI6MTY5NjkzNzkxOCwiZXhwIjoxNjk2OTM3OTc4fQ.STPu8VK5hhtaczMizbOlqPIWCXKLv6R5MaTp2deXQJo1na9XuRYmNP3Lyq_-nfLl2_kf_6aud-x_IUX4pn4b0esD5WmhJ3AECD-fIui6QznaD_JC9VNjRsDW0S_7u8cknEpTSds56saoY9spq3j8StAfDMsjwvWk-3h0iu48Fwk
@refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkuZGV2Lmtvbi1zZXJ2aWNlLmNvbSIsImF1ZCI6Imtvbi1zZXJ2aWNlLmNvbSIsInN1YiI6IntcInVzZXJJZFwiOlwiNjUyMzk2NThiYzFiMDYzNGJhMzEwNGYzXCJ9IiwicHJtIjoiNjkxOTE5ZDk5YjNiZDQ1YTdiNWU2YjZjYjMyNGUyYTk4MGY5MzMxM2I5Njg4YTJhZmE2M2E4Y2M1NjM1NTY2ZTc0MjQwODI2NjQ1MThlMWQ1YjQyZjlmZDdiYTdlMzE3MDU1M2U0OTY0NTY4OTQyODM4YWI1ODAwNDc3N2ZhZjEiLCJpYXQiOjE2OTcwNDcyNzksImV4cCI6MTY5NzY1MjA3OX0.YoLHQAk0lS5zeS5QlfT5Ox9iQ_FKtZT2a-oUwVN6Qgu8aQT7-0FmvraqhumtyJYuLjyPgS4SY-UXDW_h_rOKs2FBALQPDnRyWfZKaQkYpqaWMcHl3-qoO1xxxFpQmrnl66ZC6FCgt-JqicxdG-LUGM8WTkNhOFT3K22zJHyU4fA

GET {{url}}/me
x-token: {{refreshToken}}

###
GET {{url}}/checkhealth

###
GET {{url}}/auth/refreshtoken
Content-Type: application/json
x-token: {{refreshToken}}

###
POST {{url}}/auth/signinwithusername
Content-Type: application/json

{
  "username": "khakhung",
  "password": "123abcxxx"
}

###
POST {{url}}/auth/signup
Content-Type: application/json

{
  "userId": "nghiango",
  "username": "nghiango",
  "phone": "09848935095",
  "displayName": "Nghia Ngo",
  "email": "khabdcd@xyz.com",
  "password": "123abcxxx",
  "repeat_password": "123abcxxx"
}
