name: Docker image build and push

on:
  push:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
          chmod +x ./scripts/test.sh
          ./scripts/test.sh
        shell: bash

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Use tag
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo ${{steps.checkout.outputs}}
          echo 'TESTTTTTTTTTT'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:latest

