@urlPro=https://kon-service-q2bs.onrender.com

POST {{urlPro}}/api/v1/auth/signinwithusername
Content-Type: application/json

{
  "username": "khakhung",
  "password": "123abcxxx"
}


###
# LOGIN:
#
POST {{urlPro}}/api/v1/auth/signin
Content-Type: application/json

{
  "username": "nghiadt",
  "password": "Changeit"
}

###
# LoGIN with email
#
POST {{urlPro}}/api/v1/auth/signinwithemail
Content-Type: application/json 

{
  "email": "nghiadt@gmail.com",
  "password": "123abcXYZ"
}

###
# LOGIN with phone
#
POST {{urlPro}}/api/v1/auth/signinwithphone
Content-Type: application/json

{
  "phone": "0999999999",
  "password": "Changeit"
}